# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 207f0b067a98d684d4f77b2c93020e63f848befad1ffad6e5a4d5403747bd7d13dd411da88c9be9eb3c4f4711e59c674fc81c00b6ee73183f8f078844cb6ab15

test:
  secret_key_base: bb8d4b5f7adda770bb2c397c257e6d7e89e39834c58e92de59facc50c66f7feb3e7c291178def98b75f6b6aa7c98b622d0ce762b90c9a2d9dbe045ce621a692d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
